"""
Django settings for Manual_attendance project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qkm@_9j@q+0_ln3s9(#(40xkq-tbm9!bi$o^_#u*puojo&9hs&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['prasad-manual-4.onrender.com','localhost','127.0.0.1','prasad-manual-3.onrender.com']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'import_export',
    'Manual_attendance.Phase1',
    'Manual_attendance.Phase2',
    'Manual_attendance.Phase3_P1',
    'Manual_attendance.Phase3_P2',
    'Manual_attendance.integration',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]


CORS_ALLOW_ALL_ORIGINS = True

# CORS_ALLOWED_ORIGINS = [
#     'http://localhost:3000',  # Your frontend URL
# ]


ROOT_URLCONF = 'Manual_attendance.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Manual_attendance.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'attendance_default',
        'USER': 'admin',
        'PASSWORD': 'Salman20031804',
        'HOST': 'manual-attendance.c3u6s0ggeu6m.eu-north-1.rds.amazonaws.com',
        'PORT': '3306',
        'OPTIONS': {
            'ssl': {
                'ca': r'D:\MO Internship\eu-north-1-bundle.pem',
            },
            'sql_mode': 'STRICT_TRANS_TABLES',  # Enable strict mode
        },
    },
    'phase1': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'phase1_db',
        'USER': 'admin',
        'PASSWORD': 'Salman20031804',
        'HOST': 'manual-attendance.c3u6s0ggeu6m.eu-north-1.rds.amazonaws.com',
        'PORT': '3306',
        'OPTIONS': {
            'ssl': {
                'ca': r'D:\MO Internship\eu-north-1-bundle.pem',
            },
            'sql_mode': 'STRICT_TRANS_TABLES',  # Enable strict mode
        },
    },
    'phase2': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'phase2_db',
        'USER': 'admin',
        'PASSWORD': 'Salman20031804',
        'HOST': 'manual-attendance.c3u6s0ggeu6m.eu-north-1.rds.amazonaws.com',
        'PORT': '3306',
        'OPTIONS': {
            'ssl': {
                'ca': r'D:\MO Internship\eu-north-1-bundle.pem',
            },
            'sql_mode': 'STRICT_TRANS_TABLES',  # Enable strict mode
        },
    },
    'phase3_p1': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'phase3_p1_db',
        'USER': 'admin',
        'PASSWORD': 'Salman20031804',
        'HOST': 'manual-attendance.c3u6s0ggeu6m.eu-north-1.rds.amazonaws.com',
        'PORT': '3306',
        'OPTIONS': {
            'ssl': {
                'ca': r'D:\MO Internship\eu-north-1-bundle.pem',
            },
            'sql_mode': 'STRICT_TRANS_TABLES',  # Enable strict mode
        },
    },
    'phase3_p2': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'phase3_p2_db',
        'USER': 'admin',
        'PASSWORD': 'Salman20031804',
        'HOST': 'manual-attendance.c3u6s0ggeu6m.eu-north-1.rds.amazonaws.com',
        'PORT': '3306',
        'OPTIONS': {
            'ssl': {
                'ca': r'D:\MO Internship\eu-north-1-bundle.pem',
            },
            'sql_mode': 'STRICT_TRANS_TABLES',  # Enable strict mode
        },
    },
}

DATABASE_ROUTERS = [
    'Manual_attendance.Phase1.routers.Phase1DatabaseRouter',
    'Manual_attendance.Phase2.routers.Phase2DatabaseRouter',
    'Manual_attendance.Phase3_P1.routers.Phase3P1DatabaseRouter',
    'Manual_attendance.Phase3_P2.routers.Phase3P2DatabaseRouter',
]



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
