# Generated by Django 5.0.7 on 2024-11-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('phase', models.CharField(max_length=20)),
                ('subject_name', models.CharField(max_length=100)),
                ('time_slot', models.CharField(max_length=20)),
                ('roll_no', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], max_length=1)),
            ],
            options={
                'unique_together': {('date', 'phase', 'roll_no', 'time_slot')},
            },
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=20)),
                ('roll_no', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('fathers_name', models.CharField(max_length=100)),
                ('student_mobile', models.CharField(max_length=15)),
                ('father_mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
            ],
            options={
                'unique_together': {('phase', 'roll_no')},
            },
        ),
    ]
