# Generated by Django 5.0.7 on 2024-11-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phase2', '0002_communitymedicine_eca_forensicmedandtc_medicine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase2student',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
