# Generated by Django 5.0.7 on 2024-11-17 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phase3_P2Student',
            fields=[
                ('roll_no', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('fathers_name', models.CharField(max_length=100)),
                ('student_mobile', models.CharField(max_length=15)),
                ('father_mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Paediatrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(editable=False, max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Leave')], max_length=1)),
                ('roll_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Phase3_P2.phase3_p2student')),
            ],
            options={
                'unique_together': {('roll_number', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Orthopaedics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(editable=False, max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Leave')], max_length=1)),
                ('roll_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Phase3_P2.phase3_p2student')),
            ],
            options={
                'unique_together': {('roll_number', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Ophthalmology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(editable=False, max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Leave')], max_length=1)),
                ('roll_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Phase3_P2.phase3_p2student')),
            ],
            options={
                'unique_together': {('roll_number', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ObsAndGyn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(editable=False, max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Leave')], max_length=1)),
                ('roll_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Phase3_P2.phase3_p2student')),
            ],
            options={
                'unique_together': {('roll_number', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(editable=False, max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Leave')], max_length=1)),
                ('roll_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Phase3_P2.phase3_p2student')),
            ],
            options={
                'unique_together': {('roll_number', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(editable=False, max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Leave')], max_length=1)),
                ('roll_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Phase3_P2.phase3_p2student')),
            ],
            options={
                'unique_together': {('roll_number', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Dermatology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(editable=False, max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Leave')], max_length=1)),
                ('roll_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Phase3_P2.phase3_p2student')),
            ],
            options={
                'unique_together': {('roll_number', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Anaesthsiology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(editable=False, max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Leave')], max_length=1)),
                ('roll_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Phase3_P2.phase3_p2student')),
            ],
            options={
                'unique_together': {('roll_number', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Psychiatry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(editable=False, max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Leave')], max_length=1)),
                ('roll_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Phase3_P2.phase3_p2student')),
            ],
            options={
                'unique_together': {('roll_number', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Radiology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(editable=False, max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Leave')], max_length=1)),
                ('roll_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Phase3_P2.phase3_p2student')),
            ],
            options={
                'unique_together': {('roll_number', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(editable=False, max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Leave')], max_length=1)),
                ('roll_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Phase3_P2.phase3_p2student')),
            ],
            options={
                'unique_together': {('roll_number', 'date')},
            },
        ),
    ]
